# Jekyll configuration

name: Bad Hombre's Blog
description: Hombres CTF Team / General Bad Asses

# Url is currently only used only for the RSS feed in feed.xml
#url: http://blah
url: https://bad-hombres.github.io/

# For a project page here should be a project name. Otherwise (for user's/organizaion's page leave it empty)
baseurl: 'blog'

share:
  facebook: true
  twitter: true
  gplus: true
  linkedin: true
  pinterest: true
  email: true

social:
  github: 'bad-hombres'
  rss: feed.xml

# Google Analytics key, leave blank to ignore
google_analytics_key: UA-99735361-1
# Yandex metrika (https://metrica.yandex.com/) leave blank to ignore or put true to use
yandex_metrica:


# Set this to your disqus shortname to enable comments. Note that the 'comments'
# setting below must also be true. Individual posts can override 'comments' to
# disable on a post-by-post basis
disqus: bad-hombres
comments: true

#permalink: /:year/:month/:title

# Enable for using pages, more details are here: http://jekyllrb.com/docs/pagination/
#paginate: 3

#highlighter: rouge

markdown: kramdown
kramdown:
  input: GFM # Enable GitHub Flavored Markdown (fenced code blocks)

gems:
  - jekyll-feed
exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - LICENSE
